package com.nzion.repository.notifier.utility;

public enum TemplateNames {
    PLACE_LAB_ORDER_SMS_TO_LAB_ADMIN,
    PLACE_LAB_ORDER_SMS_TO_PATIENT,
    PLACE_RADIOLOGY_ORDER_EMAIL_TO_PATIENT,
    RESCHEDULE_LAB_ORDER_SMS_TO_LAB_ADMIN,
    RESCHEDULE_LAB_ORDER_SMS_TO_PHLEBOTOMIST,
    RESCHEDULE_LAB_ORDER_SMS_TO_PATIENT
}
